---

awscli: awscli
boto: python3-boto3
columnstore_cnf: /etc/my.cnf.d/columnstore.cnf
dlm: https://repo.cloudlinux.com/cloudlinux/8.3/BaseOS/x86_64/os/Packages/dlm-4.0.9-3.el8.x86_64.rpm
dlm_lib: https://repo.cloudlinux.com/cloudlinux/8.3/BaseOS/x86_64/os/Packages/dlm-lib-4.0.9-3.el8.x86_64.rpm
fence_agent: fence-agents-aws
gcc: gcc
gfs2: gfs2-utils
git: git
htop: htop
jemalloc: jemalloc
jq: jq
lvm2: lvm2-lockd
mariadb_backup: MariaDB-backup
mariadb_client: MariaDB-client
mariadb_columnstore_cmapi: MariaDB-columnstore-cmapi
mariadb_columnstore: MariaDB-columnstore-engine
mariadb_libs: mariadb-libs
mariadb_repo: /etc/yum.repos.d/mariadb.repo
mariadb_server: MariaDB-server
mariadb_shared: MariaDB-shared
mariadb_socket: /var/lib/mysql/mysql.sock
maxscale: maxscale
mlocate: mlocate
nano: nano
nfs_utils: nfs-utils
pcs: pcs
pcp_zeroconf: pcp-zeroconf
pre_task: dnf -y install epel-release && dnf -y install glibc-locale-source glibc-langpack-en python3 libxcrypt-compat
python_dev: platform-python-devel
python_mysql: python3-PyMySQL
python_requests: python3-requests
server_cnf: /etc/my.cnf.d/server.cnf
storagemanager_cnf: /etc/columnstore/storagemanager.cnf
tar: tar
unzip: unzip
user: mariadb
version: 8
wget: wget
os_user: rocky